/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <netinet/ip_icmp.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <android/log.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <netinet/ip.h>
#include <netdb.h>
#include<android/log.h>
/* Header for class com_haier_networkdetect_networkdetect_NativeNetworkUtils */

#ifndef _Included_com_haier_networkdetect_networkdetect_NativeNetworkUtils
#define _Included_com_haier_networkdetect_networkdetect_NativeNetworkUtils
#ifndef DEBUG
#define DEBUG 1
#endif
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_haier_networkdetect_networkdetect_NativeNetworkUtils_networkDetectInit
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_haier_networkdetect_networkdetect_NativeNetworkUtils_networkDetectSetIP1
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_haier_networkdetect_networkdetect_NativeNetworkUtils_networkDetectSetIP2
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_haier_networkdetect_networkdetect_NativeNetworkUtils_networkDetectThreadStart
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_haier_networkdetect_networkdetect_NativeNetworkUtils_networkDetectThreadStop
  (JNIEnv *, jobject);
void* thread_network_exec();
unsigned short cal_chksum(unsigned short *,int );
int pack(int ,char *);
int unpack(int ,char *,int );
int send_packet(int ,char *,int );
int recv_packet(int ,char *,int );
void _CloseSocket(int );
#ifdef __cplusplus
}
#endif
#endif
